# Build stage
FROM node:22 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

# Production stage
FROM node:22 AS production
WORKDIR /app
COPY --from=build /app/. ./
RUN npm install
CMD ["node", "dist/index.js"]
