name: Build & Publish Image 

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag based on branch
        id: vars
        run: |
          echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "branch_tag=production" >> $GITHUB_OUTPUT
          else
            echo "branch_tag=staging" >> $GITHUB_OUTPUT
          fi

      - name: Build image
        run: |
          IMAGE=ghcr.io/nikelaz/bw-backend-service
          docker build -t $IMAGE:${{ steps.vars.outputs.sha }} -f Dockerfile.prod .
          docker tag $IMAGE:${{ steps.vars.outputs.sha }} $IMAGE:${{ steps.vars.outputs.branch_tag }}

      - name: Push images
        run: |
          IMAGE=ghcr.io/nikelaz/bw-backend-service
          docker push $IMAGE:${{ steps.vars.outputs.sha }}
          docker push $IMAGE:${{ steps.vars.outputs.branch_tag }}
